export default [
  {
    nom: "Afghanistan",
    nomAlpha: "Afghanistan",
    code: "AFG",
    article: "l'",
    nomLong: "République islamique d'Afghanistan",
    capitale: "Kaboul",
  },
  {
    nom: "Afrique du Sud",
    nomAlpha: "Afrique du Sud",
    code: "ZAF",
    article: "l'",
    nomLong: "République d'Afrique du Sud",
    capitale: "Prétoria",
  },
  {
    nom: "Albanie",
    nomAlpha: "Albanie",
    code: "ALB",
    article: "l'",
    nomLong: "République d'Albanie",
    capitale: "Tirana",
  },
  {
    nom: "Algérie",
    nomAlpha: "Algérie",
    code: "DZA",
    article: "l'",
    nomLong: "République algérienne démocratique et populaire",
    capitale: "Alger",
  },
  {
    nom: "Allemagne",
    nomAlpha: "Allemagne",
    code: "DEU",
    article: "l'",
    nomLong: "République fédérale d'Allemagne",
    capitale: "Berlin",
  },
  {
    nom: "Andorre",
    nomAlpha: "Andorre",
    code: "AND",
    article: "l'",
    nomLong: "Principauté d'Andorre",
    capitale: "Andorre-la-Vieille",
  },
  {
    nom: "Angola",
    nomAlpha: "Angola",
    code: "AGO",
    article: "l'",
    nomLong: "République d'Angola",
    capitale: "Luanda",
  },
  {
    nom: "Antigua-et-Barbuda",
    nomAlpha: "Antigua-et-Barbuda",
    code: "ATG",
    article: "",
    nomLong: "Antigua-et-Barbuda",
    capitale: "Saint John's",
  },
  {
    nom: "Arabie saoudite",
    nomAlpha: "Arabie saoudite",
    code: "SAU",
    article: "l'",
    nomLong: "Royaume d'Arabie saoudite",
    capitale: "Riyad",
  },
  {
    nom: "Argentine",
    nomAlpha: "Argentine",
    code: "ARG",
    article: "l'",
    nomLong: "République argentine",
    capitale: "Buenos Aires",
  },
  {
    nom: "Arménie",
    nomAlpha: "Arménie",
    code: "ARM",
    article: "l'",
    nomLong: "République d'Arménie",
    capitale: "Erevan",
  },
  {
    nom: "Australie",
    nomAlpha: "Australie",
    code: "AUS",
    article: "l'",
    nomLong: "Commonwealth d'Australie",
    capitale: "Canberra",
  },
  {
    nom: "Autriche",
    nomAlpha: "Autriche",
    code: "AUT",
    article: "l'",
    nomLong: "République d'Autriche",
    capitale: "Vienne",
  },
  {
    nom: "Azerbaïdjan",
    nomAlpha: "Azerbaïdjan",
    code: "AZE",
    article: "l'",
    nomLong: "République d'Azerbaïdjan",
    capitale: "Bakou",
  },
  {
    nom: "Bahamas",
    nomAlpha: "Bahamas",
    code: "BHS",
    article: "les",
    nomLong: "Commonwealth des Bahamas",
    capitale: "Nassau",
  },
  {
    nom: "Bahreïn",
    nomAlpha: "Bahreïn",
    code: "BHR",
    article: "",
    nomLong: "Royaume de Bahreïn",
    capitale: "Manama",
  },
  {
    nom: "Bangladesh",
    nomAlpha: "Bangladesh",
    code: "BGD",
    article: "l'",
    nomLong: "République populaire du Bangladesh",
    capitale: "Dacca",
  },
  {
    nom: "Barbade",
    nomAlpha: "Barbade",
    code: "BRB",
    article: "la",
    nomLong: "Barbade",
    capitale: "Bridgetown",
  },
  {
    nom: "Belgique",
    nomAlpha: "Belgique",
    code: "BEL",
    article: "la",
    nomLong: "Royaume de Belgique",
    capitale: "Bruxelles",
  },
  {
    nom: "Bélize",
    nomAlpha: "Bélize",
    code: "BLZ",
    article: "le",
    nomLong: "Bélize",
    capitale: "Belmopan",
  },
  {
    nom: "Bénin",
    nomAlpha: "Bénin",
    code: "BEN",
    article: "le",
    nomLong: "République du Bénin",
    capitale: "Porto-Novo",
  },
  {
    nom: "Bhoutan",
    nomAlpha: "Bhoutan",
    code: "BTN",
    article: "le",
    nomLong: "Royaume du Bhoutan",
    capitale: "Thimphou",
  },
  {
    nom: "Biélorussie",
    nomAlpha: "Biélorussie",
    code: "BLR",
    article: "la",
    nomLong: "République de Biélorussie",
    capitale: "Minsk",
  },
  {
    nom: "Birmanie",
    nomAlpha: "Birmanie",
    code: "MMR",
    article: "la",
    nomLong: "République de l'Union de Birmanie",
    capitale: "Naypyidaw",
  },
  {
    nom: "Bolivie",
    nomAlpha: "Bolivie",
    code: "BOL",
    article: "la",
    nomLong: "État plurinational de Bolivie",
    capitale: "Sucre / La Paz",
  },
  {
    nom: "Bosnie-Herzégovine",
    nomAlpha: "Bosnie-Herzégovine",
    code: "BIH",
    article: "la",
    nomLong: "Bosnie-Herzégovine",
    capitale: "Sarajevo",
  },
  {
    nom: "Botswana",
    nomAlpha: "Botswana",
    code: "BWA",
    article: "le",
    nomLong: "République du Botswana",
    capitale: "Gaborone",
  },
  {
    nom: "Brésil",
    nomAlpha: "Brésil",
    code: "BRA",
    article: "le",
    nomLong: "République fédérative du Brésil",
    capitale: "Brasilia",
  },
  {
    nom: "Brunei",
    nomAlpha: "Brunei",
    code: "BRN",
    article: "le",
    nomLong: "Brunei Darussalam",
    capitale: "Bandar Seri Begawan",
  },
  {
    nom: "Bulgarie",
    nomAlpha: "Bulgarie",
    code: "BGR",
    article: "la",
    nomLong: "République de Bulgarie",
    capitale: "Sofia",
  },
  {
    nom: "Burkina",
    nomAlpha: "Burkina",
    code: "BFA",
    article: "le",
    nomLong: "Burkina Faso",
    capitale: "Ouagadougou",
  },
  {
    nom: "Burundi",
    nomAlpha: "Burundi",
    code: "BDI",
    article: "le",
    nomLong: "République du Burundi",
    capitale: "Gitega",
  },
  {
    nom: "Cambodge",
    nomAlpha: "Cambodge",
    code: "KHM",
    article: "le",
    nomLong: "Royaume du Cambodge",
    capitale: "Phnom Penh",
  },
  {
    nom: "Cameroun",
    nomAlpha: "Cameroun",
    code: "CMR",
    article: "le",
    nomLong: "République du Cameroun",
    capitale: "Yaoundé",
  },
  {
    nom: "Canada",
    nomAlpha: "Canada",
    code: "CAN",
    article: "le",
    nomLong: "Canada",
    capitale: "Ottawa",
  },
  {
    nom: "Cap-Vert",
    nomAlpha: "Cap-Vert",
    code: "CPV",
    article: "le",
    nomLong: "République du Cap-Vert",
    capitale: "Praia",
  },
  {
    nom: "Centrafrique",
    nomAlpha: "Centrafrique",
    code: "CAF",
    article: "la",
    nomLong: "République centrafricaine",
    capitale: "Bangui",
  },
  {
    nom: "Chili",
    nomAlpha: "Chili",
    code: "CHL",
    article: "le",
    nomLong: "République du Chili",
    capitale: "Santiago",
  },
  {
    nom: "Chine",
    nomAlpha: "Chine",
    code: "CHN",
    article: "la",
    nomLong: "République populaire de Chine",
    capitale: "Pékin",
  },
  {
    nom: "Chypre",
    nomAlpha: "Chypre",
    code: "CYP",
    article: "",
    nomLong: "République de Chypre",
    capitale: "Nicosie",
  },
  {
    nom: "Colombie",
    nomAlpha: "Colombie",
    code: "COL",
    article: "la",
    nomLong: "République de Colombie",
    capitale: "Bogota",
  },
  {
    nom: "Comores",
    nomAlpha: "Comores",
    code: "COM",
    article: "les",
    nomLong: "Union des Comores",
    capitale: "Moroni",
  },
  {
    nom: "Congo",
    nomAlpha: "Congo",
    code: "COG",
    article: "le",
    nomLong: "République du Congo",
    capitale: "Brazzaville",
  },
  {
    nom: "République démocratique du Congo",
    nomAlpha: "Congo (République démocratique du)",
    code: "COD",
    article: "la",
    nomLong: "République démocratique du Congo",
    capitale: "Kinshasa",
  },
  {
    nom: "Îles Cook",
    nomAlpha: "Cook (Îles)",
    code: "COK",
    article: "les",
    nomLong: "Îles Cook",
    capitale: "Avarua",
  },
  {
    nom: "Corée du Nord",
    nomAlpha: "Corée du Nord",
    code: "PRK",
    article: "la",
    nomLong: "République populaire démocratique de Corée",
    capitale: "Pyongyang",
  },
  {
    nom: "Corée du Sud",
    nomAlpha: "Corée du Sud",
    code: "KOR",
    article: "la",
    nomLong: "République de Corée",
    capitale: "Séoul",
  },
  {
    nom: "Costa Rica",
    nomAlpha: "Costa Rica",
    code: "CRI",
    article: "le",
    nomLong: "République du Costa Rica",
    capitale: "San José",
  },
  {
    nom: "Côte d'Ivoire",
    nomAlpha: "Côte d'Ivoire",
    code: "CIV",
    article: "la",
    nomLong: "République de Côte d'Ivoire",
    capitale: "Yamoussoukro",
  },
  {
    nom: "Croatie",
    nomAlpha: "Croatie",
    code: "HRV",
    article: "la",
    nomLong: "République de Croatie",
    capitale: "Zagreb",
  },
  {
    nom: "Cuba",
    nomAlpha: "Cuba",
    code: "CUB",
    article: "",
    nomLong: "République de Cuba",
    capitale: "La Havane",
  },
  {
    nom: "Danemark",
    nomAlpha: "Danemark",
    code: "DNK",
    article: "le",
    nomLong: "Royaume du Danemark",
    capitale: "Copenhague",
  },
  {
    nom: "Djibouti",
    nomAlpha: "Djibouti",
    code: "DJI",
    article: "le",
    nomLong: "République de Djibouti",
    capitale: "Djibouti",
  },
  {
    nom: "République dominicaine",
    nomAlpha: "Dominicaine (République)",
    code: "DOM",
    article: "la",
    nomLong: "République dominicaine",
    capitale: "Saint-Domingue",
  },
  {
    nom: "Dominique",
    nomAlpha: "Dominique",
    code: "DMA",
    article: "la",
    nomLong: "Commonwealth de la Dominique",
    capitale: "Roseau",
  },
  {
    nom: "Égypte",
    nomAlpha: "Égypte",
    code: "EGY",
    article: "l'",
    nomLong: "République arabe d'Égypte",
    capitale: "Le Caire",
  },
  {
    nom: "Émirats arabes unis",
    nomAlpha: "Émirats arabes unis",
    code: "ARE",
    article: "les",
    nomLong: "Émirats arabes unis",
    capitale: "Abou Dabi",
  },
  {
    nom: "Équateur",
    nomAlpha: "Équateur",
    code: "ECU",
    article: "l'",
    nomLong: "République d'Équateur",
    capitale: "Quito",
  },
  {
    nom: "Érythrée",
    nomAlpha: "Érythrée",
    code: "ERI",
    article: "l'",
    nomLong: "État d'Érythrée",
    capitale: "Asmara",
  },
  {
    nom: "Espagne",
    nomAlpha: "Espagne",
    code: "ESP",
    article: "l'",
    nomLong: "Royaume d'Espagne",
    capitale: "Madrid",
  },
  {
    nom: "Estonie",
    nomAlpha: "Estonie",
    code: "EST",
    article: "l'",
    nomLong: "République d'Estonie",
    capitale: "Tallinn",
  },
  {
    nom: "Eswatini",
    nomAlpha: "Eswatini",
    code: "SWZ",
    article: "le",
    nomLong: "Royaume d'Eswatini",
    capitale: "Mbabané",
  },
  {
    nom: "États-Unis",
    nomAlpha: "États-Unis",
    code: "USA",
    article: "les",
    nomLong: "États-Unis d'Amérique",
    capitale: "Washington",
  },
  {
    nom: "Éthiopie",
    nomAlpha: "Éthiopie",
    code: "ETH",
    article: "l'",
    nomLong: "République démocratique fédérale d'Éthiopie",
    capitale: "Addis Abeba",
  },
  {
    nom: "Fidji",
    nomAlpha: "Fidji",
    code: "FJI",
    article: "les",
    nomLong: "République des Fidji",
    capitale: "Suva",
  },
  {
    nom: "Finlande",
    nomAlpha: "Finlande",
    code: "FIN",
    article: "la",
    nomLong: "République de Finlande",
    capitale: "Helsinki",
  },
  {
    nom: "France",
    nomAlpha: "France",
    code: "FRA",
    article: "la",
    nomLong: "République française",
    capitale: "Paris",
  },
  {
    nom: "Gabon",
    nomAlpha: "Gabon",
    code: "GAB",
    article: "le",
    nomLong: "République gabonaise",
    capitale: "Libreville",
  },
  {
    nom: "Gambie",
    nomAlpha: "Gambie",
    code: "GMB",
    article: "la",
    nomLong: "République de Gambie",
    capitale: "Banjul",
  },
  {
    nom: "Géorgie",
    nomAlpha: "Géorgie",
    code: "GEO",
    article: "la",
    nomLong: "Géorgie",
    capitale: "Tbilissi",
  },
  {
    nom: "Ghana",
    nomAlpha: "Ghana",
    code: "GHA",
    article: "le",
    nomLong: "République du Ghana",
    capitale: "Accra",
  },
  {
    nom: "Grèce",
    nomAlpha: "Grèce",
    code: "GRC",
    article: "la",
    nomLong: "République hellénique",
    capitale: "Athènes",
  },
  {
    nom: "Grenade",
    nomAlpha: "Grenade",
    code: "GRD",
    article: "la",
    nomLong: "Grenade",
    capitale: "Saint-Georges",
  },
  {
    nom: "Guatémala",
    nomAlpha: "Guatémala",
    code: "GTM",
    article: "le",
    nomLong: "République du Guatémala",
    capitale: "Guatémala",
  },
  {
    nom: "Guinée",
    nomAlpha: "Guinée",
    code: "GIN",
    article: "la",
    nomLong: "République de Guinée",
    capitale: "Conakry",
  },
  {
    nom: "Guinée équatoriale",
    nomAlpha: "Guinée équatoriale",
    code: "GNQ",
    article: "la",
    nomLong: "République de Guinée équatoriale",
    capitale: "Malabo",
  },
  {
    nom: "Guinée-Bissao",
    nomAlpha: "Guinée-Bissao",
    code: "GNB",
    article: "la",
    nomLong: "République de Guinée-Bissao",
    capitale: "Bissao",
  },
  {
    nom: "Guyana",
    nomAlpha: "Guyana",
    code: "GUY",
    article: "le",
    nomLong: "République coopérative du Guyana",
    capitale: "Georgetown",
  },
  {
    nom: "Haïti",
    nomAlpha: "Haïti",
    code: "HTI",
    article: "",
    nomLong: "République d'Haïti",
    capitale: "Port-au-Prince",
  },
  {
    nom: "Honduras",
    nomAlpha: "Honduras",
    code: "HND",
    article: "le",
    nomLong: "République du Honduras",
    capitale: "Tégucigalpa",
  },
  {
    nom: "Hongrie",
    nomAlpha: "Hongrie",
    code: "HUN",
    article: "la",
    nomLong: "Hongrie",
    capitale: "Budapest",
  },
  {
    nom: "Inde",
    nomAlpha: "Inde",
    code: "IND",
    article: "l'",
    nomLong: "République de l'Inde",
    capitale: "New Delhi",
  },
  {
    nom: "Indonésie",
    nomAlpha: "Indonésie",
    code: "IDN",
    article: "l'",
    nomLong: "République d'Indonésie",
    capitale: "Jakarta",
  },
  {
    nom: "Irak",
    nomAlpha: "Irak",
    code: "IRQ",
    article: "l'",
    nomLong: "République d'Irak",
    capitale: "Bagdad",
  },
  {
    nom: "Iran",
    nomAlpha: "Iran",
    code: "IRN",
    article: "l'",
    nomLong: "République islamique d'Iran",
    capitale: "Téhéran",
  },
  {
    nom: "Irlande",
    nomAlpha: "Irlande",
    code: "IRL",
    article: "l'",
    nomLong: "Irlande",
    capitale: "Dublin",
  },
  {
    nom: "Islande",
    nomAlpha: "Islande",
    code: "ISL",
    article: "l'",
    nomLong: "République d'Islande",
    capitale: "Reykjavik",
  },
  {
    nom: "Israël",
    nomAlpha: "Israël",
    code: "ISR",
    article: "",
    nomLong: "État d'Israël",
    capitale: "",
  },
  {
    nom: "Italie",
    nomAlpha: "Italie",
    code: "ITA",
    article: "l'",
    nomLong: "République italienne",
    capitale: "Rome",
  },
  {
    nom: "Jamaïque",
    nomAlpha: "Jamaïque",
    code: "JAM",
    article: "la",
    nomLong: "Jamaïque",
    capitale: "Kingston",
  },
  {
    nom: "Japon",
    nomAlpha: "Japon",
    code: "JPN",
    article: "le",
    nomLong: "Japon",
    capitale: "Tokyo",
  },
  {
    nom: "Jordanie",
    nomAlpha: "Jordanie",
    code: "JOR",
    article: "la",
    nomLong: "Royaume hachémite de Jordanie",
    capitale: "Amman",
  },
  {
    nom: "Kazakhstan",
    nomAlpha: "Kazakhstan",
    code: "KAZ",
    article: "le",
    nomLong: "République du Kazakhstan",
    capitale: "Nour-Soultan",
  },
  {
    nom: "Kénya",
    nomAlpha: "Kénya",
    code: "KEN",
    article: "le",
    nomLong: "République du Kénya",
    capitale: "Nairobi",
  },
  {
    nom: "Kirghizstan",
    nomAlpha: "Kirghizstan",
    code: "KGZ",
    article: "le",
    nomLong: "République kirghize",
    capitale: "Bichkek",
  },
  {
    nom: "Kiribati",
    nomAlpha: "Kiribati",
    code: "KIR",
    article: "les",
    nomLong: "République des Kiribati",
    capitale: "Bairiki",
  },
  {
    nom: "Kosovo",
    nomAlpha: "Kosovo",
    code: "KOS",
    article: "le",
    nomLong: "République du Kosovo",
    capitale: "Pristina",
  },
  {
    nom: "Koweït",
    nomAlpha: "Koweït",
    code: "KWT",
    article: "le",
    nomLong: "État du Koweït",
    capitale: "Koweït",
  },
  {
    nom: "Laos",
    nomAlpha: "Laos",
    code: "LAO",
    article: "le",
    nomLong: "République démocratique populaire lao",
    capitale: "Vientiane",
  },
  {
    nom: "Lésotho",
    nomAlpha: "Lésotho",
    code: "LSO",
    article: "le",
    nomLong: "Royaume du Lesotho",
    capitale: "Maséru",
  },
  {
    nom: "Lettonie",
    nomAlpha: "Lettonie",
    code: "LVA",
    article: "la",
    nomLong: "République de Lettonie",
    capitale: "Riga",
  },
  {
    nom: "Liban",
    nomAlpha: "Liban",
    code: "LBN",
    article: "le",
    nomLong: "République libanaise",
    capitale: "Beyrouth",
  },
  {
    nom: "Libéria",
    nomAlpha: "Libéria",
    code: "LBR",
    article: "le",
    nomLong: "République du Libéria",
    capitale: "Monrovia",
  },
  {
    nom: "Libye",
    nomAlpha: "Libye",
    code: "LBY",
    article: "la",
    nomLong: "État de Libye",
    capitale: "Tripoli",
  },
  {
    nom: "Liechtenstein",
    nomAlpha: "Liechtenstein",
    code: "LIE",
    article: "le",
    nomLong: "Principauté du Liechtenstein",
    capitale: "Vaduz",
  },
  {
    nom: "Lituanie",
    nomAlpha: "Lituanie",
    code: "LTU",
    article: "la",
    nomLong: "République de Lituanie",
    capitale: "Vilnius",
  },
  {
    nom: "Luxembourg",
    nomAlpha: "Luxembourg",
    code: "LUX",
    article: "le",
    nomLong: "Grand-Duché de Luxembourg",
    capitale: "Luxembourg",
  },
  {
    nom: "Macédoine du Nord",
    nomAlpha: "Macédoine du Nord",
    code: "MKD",
    article: "l'",
    nomLong: "République de Macédoine du Nord",
    capitale: "Skopje",
  },
  {
    nom: "Madagascar",
    nomAlpha: "Madagascar",
    code: "MDG",
    article: "",
    nomLong: "République de Madagascar",
    capitale: "Antananarivo (Tananarive)",
  },
  {
    nom: "Malaisie",
    nomAlpha: "Malaisie",
    code: "MYS",
    article: "la",
    nomLong: "Malaisie",
    capitale: "Kuala Lumpur",
  },
  {
    nom: "Malawi",
    nomAlpha: "Malawi",
    code: "MWI",
    article: "le",
    nomLong: "République du Malawi",
    capitale: "Lilongwé",
  },
  {
    nom: "Maldives",
    nomAlpha: "Maldives",
    code: "MDV",
    article: "les",
    nomLong: "République des Maldives",
    capitale: "Malé",
  },
  {
    nom: "Mali",
    nomAlpha: "Mali",
    code: "MLI",
    article: "le",
    nomLong: "République du Mali",
    capitale: "Bamako",
  },
  {
    nom: "Malte",
    nomAlpha: "Malte",
    code: "MLT",
    article: "",
    nomLong: "République de Malte",
    capitale: "La Valette",
  },
  {
    nom: "Maroc",
    nomAlpha: "Maroc",
    code: "MAR",
    article: "le",
    nomLong: "Royaume du Maroc",
    capitale: "Rabat",
  },
  {
    nom: "Îles Marshall",
    nomAlpha: "Marshall (Îles)",
    code: "MHL",
    article: "les",
    nomLong: "République des Îles Marshall",
    capitale: "Delap-Uliga-Darrit",
  },
  {
    nom: "Maurice",
    nomAlpha: "Maurice",
    code: "MUS",
    article: "",
    nomLong: "République de Maurice",
    capitale: "Port-Louis",
  },
  {
    nom: "Mauritanie",
    nomAlpha: "Mauritanie",
    code: "MRT",
    article: "la",
    nomLong: "République islamique de Mauritanie",
    capitale: "Nouakchott",
  },
  {
    nom: "Mexique",
    nomAlpha: "Mexique",
    code: "MEX",
    article: "le",
    nomLong: "États-Unis du Mexique",
    capitale: "Mexico",
  },
  {
    nom: "Micronésie",
    nomAlpha: "Micronésie",
    code: "FSM",
    article: "la",
    nomLong: "États fédérés de Micronésie",
    capitale: "Palikir",
  },
  {
    nom: "Moldavie",
    nomAlpha: "Moldavie",
    code: "MDA",
    article: "la",
    nomLong: "République de Moldavie",
    capitale: "Chisinau",
  },
  {
    nom: "Monaco",
    nomAlpha: "Monaco",
    code: "MCO",
    article: "",
    nomLong: "Principauté de Monaco",
    capitale: "Monaco",
  },
  {
    nom: "Mongolie",
    nomAlpha: "Mongolie",
    code: "MNG",
    article: "la",
    nomLong: "Mongolie",
    capitale: "Oulan-Bator",
  },
  {
    nom: "Monténégro",
    nomAlpha: "Monténégro",
    code: "MNE",
    article: "le",
    nomLong: "Monténégro",
    capitale: "Podgorica",
  },
  {
    nom: "Mozambique",
    nomAlpha: "Mozambique",
    code: "MOZ",
    article: "le",
    nomLong: "République du Mozambique",
    capitale: "Maputo",
  },
  {
    nom: "Namibie",
    nomAlpha: "Namibie",
    code: "NAM",
    article: "la",
    nomLong: "République de Namibie",
    capitale: "Windhoek",
  },
  {
    nom: "Nauru",
    nomAlpha: "Nauru",
    code: "NRU",
    article: "",
    nomLong: "République de Nauru",
    capitale: "Yaren",
  },
  {
    nom: "Népal",
    nomAlpha: "Népal",
    code: "NPL",
    article: "le",
    nomLong: "République démocratique fédérale du Népal",
    capitale: "Katmandou",
  },
  {
    nom: "Nicaragua",
    nomAlpha: "Nicaragua",
    code: "NIC",
    article: "le",
    nomLong: "République du Nicaragua",
    capitale: "Managua",
  },
  {
    nom: "Niger",
    nomAlpha: "Niger",
    code: "NER",
    article: "le",
    nomLong: "République du Niger",
    capitale: "Niamey",
  },
  {
    nom: "Nigéria",
    nomAlpha: "Nigéria",
    code: "NGA",
    article: "le",
    nomLong: "République fédérale du Nigéria",
    capitale: "Abuja",
  },
  {
    nom: "Niue",
    nomAlpha: "Niue",
    code: "NIU",
    article: "",
    nomLong: "Niue",
    capitale: "Alofi",
  },
  {
    nom: "Norvège",
    nomAlpha: "Norvège",
    code: "NOR",
    article: "la",
    nomLong: "Royaume de Norvège",
    capitale: "Oslo",
  },
  {
    nom: "Nouvelle-Zélande",
    nomAlpha: "Nouvelle-Zélande",
    code: "NZL",
    article: "la",
    nomLong: "Nouvelle-Zélande",
    capitale: "Wellington",
  },
  {
    nom: "Oman",
    nomAlpha: "Oman",
    code: "OMN",
    article: "",
    nomLong: "Sultanat d'Oman",
    capitale: "Mascate",
  },
  {
    nom: "Ouganda",
    nomAlpha: "Ouganda",
    code: "UGA",
    article: "l'",
    nomLong: "République d'Ouganda",
    capitale: "Kampala",
  },
  {
    nom: "Ouzbékistan",
    nomAlpha: "Ouzbékistan",
    code: "UZB",
    article: "l'",
    nomLong: "République d'Ouzbékistan",
    capitale: "Tachkent",
  },
  {
    nom: "Pakistan",
    nomAlpha: "Pakistan",
    code: "PAK",
    article: "le",
    nomLong: "République islamique du Pakistan",
    capitale: "Islamabad",
  },
  {
    nom: "Palaos",
    nomAlpha: "Palaos",
    code: "PLW",
    article: "les",
    nomLong: "République des Palaos",
    capitale: "Melekeok",
  },
  {
    nom: "Panama",
    nomAlpha: "Panama",
    code: "PAN",
    article: "le",
    nomLong: "République du Panama",
    capitale: "Panama",
  },
  {
    nom: "Papouasie-Nouvelle-Guinée",
    nomAlpha: "Papouasie-Nouvelle-Guinée",
    code: "PNG",
    article: "la",
    nomLong: "État indépendant de Papouasie-Nouvelle-Guinée",
    capitale: "Port Moresby",
  },
  {
    nom: "Paraguay",
    nomAlpha: "Paraguay",
    code: "PRY",
    article: "le",
    nomLong: "République du Paraguay",
    capitale: "Assomption (Asuncion)",
  },
  {
    nom: "Pays-Bas",
    nomAlpha: "Pays-Bas",
    code: "NLD",
    article: "les",
    nomLong: "Royaume des Pays-Bas",
    capitale: "Amsterdam",
  },
  {
    nom: "Pérou",
    nomAlpha: "Pérou",
    code: "PER",
    article: "le",
    nomLong: "République du Pérou",
    capitale: "Lima",
  },
  {
    nom: "Philippines",
    nomAlpha: "Philippines",
    code: "PHL",
    article: "les",
    nomLong: "République des Philippines",
    capitale: "Manille",
  },
  {
    nom: "Pologne",
    nomAlpha: "Pologne",
    code: "POL",
    article: "la",
    nomLong: "République de Pologne",
    capitale: "Varsovie",
  },
  {
    nom: "Portugal",
    nomAlpha: "Portugal",
    code: "PRT",
    article: "le",
    nomLong: "République portugaise",
    capitale: "Lisbonne",
  },
  {
    nom: "Qatar",
    nomAlpha: "Qatar",
    code: "QAT",
    article: "le",
    nomLong: "État du Qatar",
    capitale: "Doha",
  },
  {
    nom: "Roumanie",
    nomAlpha: "Roumanie",
    code: "ROU",
    article: "la",
    nomLong: "Roumanie",
    capitale: "Bucarest",
  },
  {
    nom: "Royaume-Uni",
    nomAlpha: "Royaume-Uni",
    code: "GBR",
    article: "le",
    nomLong: "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
    capitale: "Londres",
  },
  {
    nom: "Russie",
    nomAlpha: "Russie",
    code: "RUS",
    article: "la",
    nomLong: "Fédération de Russie",
    capitale: "Moscou",
  },
  {
    nom: "Rwanda",
    nomAlpha: "Rwanda",
    code: "RWA",
    article: "le",
    nomLong: "République du Rwanda",
    capitale: "Kigali",
  },
  {
    nom: "Saint-Christophe-et-Niévès",
    nomAlpha: "Saint-Christophe-et-Niévès",
    code: "KNA",
    article: "",
    nomLong: "Fédération de Saint-Christophe-et-Niévès",
    capitale: "Basseterre",
  },
  {
    nom: "Sainte-Lucie",
    nomAlpha: "Sainte-Lucie",
    code: "LCA",
    article: "",
    nomLong: "Sainte-Lucie",
    capitale: "Castries",
  },
  {
    nom: "Saint-Marin",
    nomAlpha: "Saint-Marin",
    code: "SMR",
    article: "",
    nomLong: "République de Saint-Marin",
    capitale: "Saint-Marin",
  },
  {
    nom: "Saint-Vincent-et-les-Grenadines",
    nomAlpha: "Saint-Vincent-et-les-Grenadines",
    code: "VCT",
    article: "",
    nomLong: "Saint-Vincent-et-les-Grenadines",
    capitale: "Kingstown",
  },
  {
    nom: "Salomon",
    nomAlpha: "Salomon",
    code: "SLB",
    article: "les",
    nomLong: "Îles Salomon",
    capitale: "Honiara",
  },
  {
    nom: "Salvador",
    nomAlpha: "Salvador",
    code: "SLV",
    article: "le",
    nomLong: "République du Salvador",
    capitale: "San Salvador",
  },
  {
    nom: "Samoa",
    nomAlpha: "Samoa",
    code: "WSM",
    article: "les",
    nomLong: "État indépendant des Samoa",
    capitale: "Apia",
  },
  {
    nom: "Sao Tomé-et-Principe",
    nomAlpha: "Sao Tomé-et-Principe",
    code: "STP",
    article: "",
    nomLong: "République démocratique de Sao Tomé-et-Principe",
    capitale: "Sao Tomé",
  },
  {
    nom: "Sénégal",
    nomAlpha: "Sénégal",
    code: "SEN",
    article: "le",
    nomLong: "République du Sénégal",
    capitale: "Dakar",
  },
  {
    nom: "Serbie",
    nomAlpha: "Serbie",
    code: "SRB",
    article: "la",
    nomLong: "République de Serbie",
    capitale: "Belgrade",
  },
  {
    nom: "Seychelles",
    nomAlpha: "Seychelles",
    code: "SYC",
    article: "les",
    nomLong: "République des Seychelles",
    capitale: "Victoria",
  },
  {
    nom: "Sierra Leone",
    nomAlpha: "Sierra Leone",
    code: "SLE",
    article: "la",
    nomLong: "République de Sierra Leone",
    capitale: "Freetown",
  },
  {
    nom: "Singapour",
    nomAlpha: "Singapour",
    code: "SGP",
    article: "",
    nomLong: "République de Singapour",
    capitale: "Singapour",
  },
  {
    nom: "Slovaquie",
    nomAlpha: "Slovaquie",
    code: "SVK",
    article: "la",
    nomLong: "République slovaque",
    capitale: "Bratislava",
  },
  {
    nom: "Slovénie",
    nomAlpha: "Slovénie",
    code: "SVN",
    article: "la",
    nomLong: "République de Slovénie",
    capitale: "Ljubljana",
  },
  {
    nom: "Somalie",
    nomAlpha: "Somalie",
    code: "SOM",
    article: "la",
    nomLong: "République fédérale de Somalie",
    capitale: "Mogadiscio",
  },
  {
    nom: "Soudan",
    nomAlpha: "Soudan",
    code: "SDN",
    article: "le",
    nomLong: "République du Soudan",
    capitale: "Khartoum",
  },
  {
    nom: "Soudan du Sud",
    nomAlpha: "Soudan du Sud",
    code: "SDS",
    article: "le",
    nomLong: "République du Soudan du Sud",
    capitale: "Djouba",
  },
  {
    nom: "Sri Lanka",
    nomAlpha: "Sri Lanka",
    code: "LKA",
    article: "le",
    nomLong: "République démocratique socialiste du Sri Lanka",
    capitale: "Sri Jayewardenepura-Kotte",
  },
  {
    nom: "Suède",
    nomAlpha: "Suède",
    code: "SWE",
    article: "la",
    nomLong: "Royaume de Suède",
    capitale: "Stockholm",
  },
  {
    nom: "Suisse",
    nomAlpha: "Suisse",
    code: "CHE",
    article: "la",
    nomLong: "Confédération suisse",
    capitale: "Berne",
  },
  {
    nom: "Suriname",
    nomAlpha: "Suriname",
    code: "SUR",
    article: "le",
    nomLong: "République du Suriname",
    capitale: "Paramaribo",
  },
  {
    nom: "Syrie",
    nomAlpha: "Syrie",
    code: "SYR",
    article: "la",
    nomLong: "République arabe syrienne",
    capitale: "Damas",
  },
  {
    nom: "Tadjikistan",
    nomAlpha: "Tadjikistan",
    code: "TJK",
    article: "le",
    nomLong: "République du Tadjikistan",
    capitale: "Douchanbé",
  },
  {
    nom: "Tanzanie",
    nomAlpha: "Tanzanie",
    code: "TZA",
    article: "la",
    nomLong: "République unie de Tanzanie",
    capitale: "Dodoma",
  },
  {
    nom: "Tchad",
    nomAlpha: "Tchad",
    code: "TCD",
    article: "le",
    nomLong: "République du Tchad",
    capitale: "Ndjamena",
  },
  {
    nom: "Tchéquie",
    nomAlpha: "Tchéquie",
    code: "CZE",
    article: "la",
    nomLong: "République tchèque",
    capitale: "Prague",
  },
  {
    nom: "Thaïlande",
    nomAlpha: "Thaïlande",
    code: "THA",
    article: "la",
    nomLong: "Royaume de Thaïlande",
    capitale: "Bangkok",
  },
  {
    nom: "Timor oriental",
    nomAlpha: "Timor oriental",
    code: "TLS",
    article: "le",
    nomLong: "République démocratique du Timor oriental",
    capitale: "Dili",
  },
  {
    nom: "Togo",
    nomAlpha: "Togo",
    code: "TGO",
    article: "le",
    nomLong: "République togolaise",
    capitale: "Lomé",
  },
  {
    nom: "Tonga",
    nomAlpha: "Tonga",
    code: "TON",
    article: "les",
    nomLong: "Royaume des Tonga",
    capitale: "Nuku'alofa",
  },
  {
    nom: "Trinité-et-Tobago",
    nomAlpha: "Trinité-et-Tobago",
    code: "TTO",
    article: "la",
    nomLong: "République de Trinité-et-Tobago",
    capitale: "Port-d'Espagne (Port of Spain)",
  },
  {
    nom: "Tunisie",
    nomAlpha: "Tunisie",
    code: "TUN",
    article: "la",
    nomLong: "République tunisienne",
    capitale: "Tunis",
  },
  {
    nom: "Turkménistan",
    nomAlpha: "Turkménistan",
    code: "TKM",
    article: "le",
    nomLong: "Turkménistan",
    capitale: "Achgabat",
  },
  {
    nom: "Turquie",
    nomAlpha: "Turquie",
    code: "TUR",
    article: "la",
    nomLong: "République de Turquie",
    capitale: "Ankara",
  },
  {
    nom: "Tuvalu",
    nomAlpha: "Tuvalu",
    code: "TUV",
    article: "les",
    nomLong: "Tuvalu",
    capitale: "Vaiaku",
  },
  {
    nom: "Ukraine",
    nomAlpha: "Ukraine",
    code: "UKR",
    article: "l'",
    nomLong: "Ukraine",
    capitale: "Kiev",
  },
  {
    nom: "Uruguay",
    nomAlpha: "Uruguay",
    code: "URY",
    article: "l'",
    nomLong: "République orientale de l'Uruguay",
    capitale: "Montévidéo",
  },
  {
    nom: "Vanuatu",
    nomAlpha: "Vanuatu",
    code: "VUT",
    article: "le",
    nomLong: "République du Vanuatu",
    capitale: "Port-Vila",
  },
  {
    nom: "Vatican",
    nomAlpha: "Vatican",
    code: "VAT",
    article: "le",
    nomLong: "Vatican (Saint-Siège)",
    capitale: "",
  },
  {
    nom: "Vénézuéla",
    nomAlpha: "Vénézuéla",
    code: "VEN",
    article: "le",
    nomLong: "République bolivarienne du Vénézuéla",
    capitale: "Caracas",
  },
  {
    nom: "Vietnam",
    nomAlpha: "Vietnam",
    code: "VNM",
    article: "le",
    nomLong: "République socialiste du Vietnam",
    capitale: "Hanoï",
  },
  {
    nom: "Yémen",
    nomAlpha: "Yémen",
    code: "YEM",
    article: "le",
    nomLong: "République du Yémen",
    capitale: "Sanaa",
  },
  {
    nom: "Zambie",
    nomAlpha: "Zambie",
    code: "ZMB",
    article: "la",
    nomLong: "République de Zambie",
    capitale: "Lusaka",
  },
  {
    nom: "Zimbabwé",
    nomAlpha: "Zimbabwé",
    code: "ZWE",
    article: "le",
    nomLong: "République du Zimbabwé",
    capitale: "Hararé",
  },
] as const
